Defer SyncScope::mutate_* definitions until after RenderWorld is complete
Template methods of SyncScope accessed non-dependent names
m_world.m_objects etc. where m_world is RenderWorld&. Because
RenderWorld was only forward-declared at that point in the header,
Clang (Emscripten emsdk) rejected the template at parse time:

  error: member access into incomplete type 'RenderWorld'
    m_world.m_objects.mutate_at(i, std::forward<Fn>(fn));

MSVC happened to defer name lookup and let it through. Move the
template bodies out of the class, below the RenderWorld definition
in the same header.